#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &
pgrep -x picom > /dev/null || picom &
~/.config/polybar/launch.sh &
~/.config/bspwm/scripts/random_wallpaper.sh &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# BSPC Settings
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Colors
bspc config normal_border_color     "#414868"
bspc config active_border_color     "#bb9af7"
bspc config focused_border_color    "#bb9af7"
bspc config urgent_border_color     "#f7768e"
